# Generated by Django 4.2.21 on 2025-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('income', models.PositiveIntegerField()),
                ('jobs', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
    ]
