# Generated by Django 4.2.21 on 2025-06-05 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(blank=True, max_length=15, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('asset', models.PositiveIntegerField(blank=True, help_text='자산 (원 단위)', null=True)),
                ('salary', models.PositiveIntegerField(blank=True, help_text='연봉 (원 단위)', null=True)),
                ('liked_deposits', models.ManyToManyField(blank=True, related_name='liked_by_users', to='finance.depositproducts')),
                ('liked_savings', models.ManyToManyField(blank=True, related_name='liked_by_users', to='finance.savingproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
